# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-16 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Persona', '0001_initial'),
        ('Tramite', '0004_auto_20170512_0952'),
        ('TipoTramite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTramite',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField()),
                ('fecha_solicitada', models.TextField()),
                ('cant_dias', models.TextField()),
                ('motivo', models.TextField()),
                ('documentacion', models.CharField(blank=True, max_length=50, null=True)),
                ('perso_cuil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Persona.Persona')),
                ('tipo_tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TipoTramite.TipoTramite')),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tramite.Tramite')),
            ],
        ),
    ]
