# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-09 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id_tramite', models.IntegerField(primary_key=True, serialize=False)),
                ('tramite', models.CharField(max_length=30)),
                ('tipo_tramite', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_exp', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
