# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-12 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tramite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_exp', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='tipo_exp',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='tipo_tramite',
        ),
        migrations.AddField(
            model_name='tipotramite',
            name='tipo_tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tramite.Tramite'),
        ),
    ]
