# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-12 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tramite', '0003_auto_20170512_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipotramite',
            name='tramite',
        ),
        migrations.AlterField(
            model_name='tramite',
            name='id_tramite',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='TipoTramite',
        ),
    ]
