# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-12 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tramite', '0004_auto_20170512_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTramite',
            fields=[
                ('id_tipo_tramite', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_tramite', models.CharField(blank=True, max_length=50, null=True)),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tramite.Tramite')),
            ],
        ),
    ]
