# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(default=94126110, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
