# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_pago_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=datetime.date(2016, 9, 21)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2016, 10, 21)),
        ),
    ]
