# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-24 23:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0003_auto_20160921_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=datetime.date(2016, 9, 24)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2016, 10, 24)),
        ),
    ]
